# Generated by Django 3.1.5 on 2021-01-28 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieSearchApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='movieTitle',
            field=models.CharField(default='', max_length=255),
        ),
    ]
